### ISSUE TITLE
회원가입 email 2차 인증, Oauth, model 추가, 유효성검사 합치기, 중복 로그인

### ISSUE THREAD

**Issue by jmsmg** [pingpongpangpong/prototype#11]
- [x] 유효성검사 메인에 합치기
- [x] model
- [x] 2차 인증
- [x] Oauth
- [x] 다른곳에서 중복 로그인 방지 (승부 주작 방지)

**Comment by ijhyn** [comment]
- 이메일 인증 후, 확인 버튼을 누르면 아래와 같이 400 반환
![Image](https://github.com/user-attachments/assets/dd28d742-e80a-49a1-be72-f105c19bef5b)
